services:
    app:
        build: .
        ports:
            - '3001:3001'
        networks:
            - app
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_started
        env_file:
            - .env.development

    mysql:
        image: mysql:8.0
        ports:
            - '3305:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pull
            MYSQL_USER: dev
            MYSQL_PASSWORD: pass
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'mysqladmin ping -h localhost -u root --password=$MYSQL_ROOT_PASSWORD || exit 1',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app

    redis:
        image: redis:7.0
        ports:
            - '6378:6379'
        networks:
            - app

networks:
    app:
volumes:
    db:
