services:
    app:
        build: .
        ports:
            - '3001:3001'
        env_file:
            - .env.development
        networks:
            - app
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_started

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pull
            MYSQL_USER: dev
            MYSQL_PASSWORD: pass
        ports:
            - '3305:3306'
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app
    redis:
        image: redis:7
        ports:
            - '6378:6379'
        networks:
            - app

networks:
    app:
volumes:
    db_data:
