name: Node.js CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: pull
                    MYSQL_USER: dev
                    MYSQL_PASSWORD: pass
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
            redis:
                image: redis:7.0
                ports:
                    - 6379:6379
                options: >-
                    --health-cmd="redis-cli ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        env:
            NODE_ENV: development

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Run tests
              env:
                  JWT_SECRET: secret
                  WT_EXPIRES_IN: 1d
                  DB_HOST: localhost
                  DB_PORT: 3306
                  DB_NAME: pull
                  DB_USER: dev
                  DB_PASS: pass
                  DIALECT: mysql
                  REDIS_HOST: localhost
                  REDIS_PORT: 6379
              run: yarn test:cov

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build project
              run: yarn build
